apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  # References:
  # * https://github.com/argoproj/argo-workflows/blob/v3.4.16/config/config.go
  # * https://github.com/argoproj/argo-workflows/blob/v3.4.16/docs/workflow-controller-configmap.md
  # * https://github.com/argoproj/argo-workflows/blob/v3.4.16/docs/workflow-controller-configmap.yaml

  # TODO(gfrasca): remove?  Unused in v3.4
  # pns executor is a more portable default, see https://github.com/kubeflow/pipelines/issues/1654.
  # However, it is flaky for containers that run really fast, see https://github.com/kubeflow/pipelines/issues/5285.
  containerRuntimeExecutor: pns
